### ISSUE TITLE
fix your thing basel: `src_folder_path` no longer exists in config

### ISSUE THREAD

**Issue by sanamorii** [TeamLeen/Filerize#11]
i am very sleep deprived, anyways here's an issue with your ui
`src_folder_path` no longer exists in the config file - ui code tries to call it resulting in key value error. please remove
![image](https://user-images.githubusercontent.com/86570135/218294767-e82aeb46-ecf5-475f-b449-a8ae3d2cb09d.png)

**Comment by sanamorii** [comment]
@baselakasha 
fix thxs

**Comment by baselakasha** [comment]
Hi why does this config item not exist anymore?

**Comment by baselakasha** [comment]
I think is this related to the config file beign in git where it should not be becuase it is specific to the enviroment the program is running in.

**Comment by baselakasha** [comment]
https://github.com/orgs/TeamLeen/projects/1/views/1?pane=issue&itemId=20591726

**Comment by sanamorii** [comment]
Ignore this issue - was extremely sleep deprived then so I didn't know what was going through my head.
